[package]
name = "bit-vec"
version = "0.6.0"
authors = ["Alexis Beingessner <a.beingessner@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A vector of bits"
repository = "https://github.com/contain-rs/bit-vec"
homepage = "https://github.com/contain-rs/bit-vec"
documentation = "https://contain-rs.github.io/bit-vec/bit_vec"
keywords = ["data-structures", "bitvec", "bitmask", "bitmap", "bit"]
readme = "README.md"

[dev-dependencies]
rand = "0.3.15"
serde_json = "1.0"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[features]
default = ["std"]

nightly = []

std = []
